server:
  port: 18810
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: leocoder-template
  # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
  # session 配置
  session:
    store-type: redis
    # session 30 天过期 单位秒
    timeout: 2592000
  profiles:
    active: local


#mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath:/mapper/*.xml
  # 配置Mybatis数据返回类型别名（默认别名为类名）
  type-aliases-package: org.leocoder.template.domain
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


#配置控制台打印日志Debug
logging:
  level:
    org.leocoder.template.mapper: debug

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - org.leocoder.template.controller
