spring:

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://myserver.coder:3306/leocoder-template?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: gzm2001..
  redis:
    database: 10 # Redis 数据库索引（默认为 0）
    host: myserver.coder # Redis 服务器地址 127.0.0.1
    port: 6379 # Redis 服务器连接端口
    password:   # Redis 服务器连接密码（默认为空）
    timeout: 5s # 读超时时间
    connect-timeout: 5s # 链接超时时间
    lettuce:
      pool:
        max-active: 200 # 连接池最大连接数
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 10 # 连接池中的最大空闲连接